use v5.40;
use utf8;
use feature 'class';
no warnings 'portable', 'experimental::class';
use Test2::V0;
use lib 'lib';
use Brocken::AST;
subtest 'Node base class' => sub {
    my $n = Brocken::AST::Node->new( line => 10, col => 5, file => 'test.brocken' );
    is $n->line, 10,             'node line';
    is $n->col,  5,              'node col';
    is $n->file, 'test.brocken', 'node file';
    is $n->dump, 'Node',         'dump returns class name';
};
subtest 'Node defaults' => sub {
    my $n = Brocken::AST::Node->new;
    is $n->line, 0,     'default line 0';
    is $n->col,  0,     'default col 0';
    is $n->file, undef, 'default file undef';
};
subtest 'Statement nodes' => sub {
    my $block = Brocken::AST::Stmt::Block->new( statements => [] );
    ok $block->isa('Brocken::AST::Stmt::Block'), 'block isa Block';
    ok $block->statements,                       'block has statements';
    is $block->dump, 'Block', 'dump returns Block';
    my $vd = Brocken::AST::Stmt::VarDecl->new( name => '$x', type => 'Int', value => undef );
    is $vd->name, '$x',  'VarDecl name';
    is $vd->type, 'Int', 'VarDecl type';
    my $od = Brocken::AST::Stmt::OurDecl->new( name => '$y', type => 'Int', value => undef );
    is $od->name, '$y', 'OurDecl name';
    my $sd = Brocken::AST::Stmt::StateDecl->new( name => '$z', type => 'Int', value => undef );
    is $sd->name, '$z', 'StateDecl name';
    my $assign = Brocken::AST::Stmt::Assignment->new( name => '$x', value => undef );
    is $assign->name, '$x', 'Assignment name';
    my $if = Brocken::AST::Stmt::If->new( condition => undef, then_block => $block );
    is $if->condition,  undef,  'If condition';
    is $if->then_block, $block, 'If then_block';
    is $if->else_block, undef,  'If else_block default undef';
    my $while = Brocken::AST::Stmt::While->new( condition => undef, body => $block );
    is $while->body, $block, 'While body';
    my $for = Brocken::AST::Stmt::For->new( var => '$x', source => undef, body => $block );
    is $for->var,   '$x', 'For var';
    is $for->is_my, 0,    'For is_my default 0';
    my $ret = Brocken::AST::Stmt::Return->new( expr => undef );
    ok $ret->isa('Brocken::AST::Stmt::Return'), 'Return isa Return';
    my $exit = Brocken::AST::Stmt::Exit->new( expr => undef );
    ok $exit->isa('Brocken::AST::Stmt::Exit'), 'Exit isa Exit';
    my $defer = Brocken::AST::Stmt::Defer->new( block => $block );
    is $defer->block, $block, 'Defer block';
    my $use = Brocken::AST::Stmt::Use->new( package => 'Foo' );
    is $use->package, 'Foo', 'Use package';
    my $req = Brocken::AST::Stmt::Require->new( package => 'Bar' );
    is $req->package, 'Bar', 'Require package';
    my $eval = Brocken::AST::Stmt::Eval->new( code => undef );
    ok $eval->isa('Brocken::AST::Stmt::Eval'), 'Eval isa Eval';
    my $yada = Brocken::AST::Stmt::Yada->new;
    is $yada->dump, 'Yada', 'Yada created';
};
subtest 'Loop control nodes' => sub {
    my $next = Brocken::AST::Stmt::Next->new;
    ok $next->isa('Brocken::AST::Stmt::Next'), 'Next created';
    my $last = Brocken::AST::Stmt::Last->new;
    ok $last->isa('Brocken::AST::Stmt::Last'), 'Last created';
    my $redo = Brocken::AST::Stmt::Redo->new;
    ok $redo->isa('Brocken::AST::Stmt::Redo'), 'Redo created';
};
subtest 'Expression nodes' => sub {
    my $const = Brocken::AST::Expr::Const->new( value => 42, type => 'Int' );
    is $const->value, 42,    'Const value';
    is $const->type,  'Int', 'Const type';
    my $var = Brocken::AST::Expr::Var->new( name => '$x' );
    is $var->name, '$x', 'Var name';
    my $binop = Brocken::AST::Expr::BinOp->new( op => '+', left => $const, right => $const );
    is $binop->op,   '+',    'BinOp op';
    is $binop->left, $const, 'BinOp left';
    my $unary = Brocken::AST::Expr::UnaryOp->new( op => '!', expr => $var );
    is $unary->op,   '!',  'UnaryOp op';
    is $unary->expr, $var, 'UnaryOp expr';
    my $ternary = Brocken::AST::Expr::Ternary->new( cond => $var, then => $const, else => $const );
    is $ternary->cond, $var,   'Ternary cond';
    is $ternary->then, $const, 'Ternary then';
    is $ternary->else, $const, 'Ternary else';
    my $call = Brocken::AST::Expr::Call->new( name => 'say', args => [$const] );
    is $call->name, 'say', 'Call name';
    ok scalar( @{ $call->args } ) == 1, 'Call args';
    my $acall = Brocken::AST::Expr::AnonCall->new( invocant => $var, args => [] );
    is $acall->invocant, $var, 'AnonCall invocant';
    my $arr = Brocken::AST::Expr::ArrayLiteral->new( elements => [$const] );
    ok scalar( @{ $arr->elements } ) == 1, 'ArrayLiteral elements';
    my $tup = Brocken::AST::Expr::TupleLiteral->new( elements => [] );
    ok scalar( @{ $tup->elements } ) == 0, 'TupleLiteral elements';
    my $hash = Brocken::AST::Expr::HashLiteral->new( pairs => [ { key => $const, value => $const } ] );
    ok scalar( @{ $hash->pairs } ) == 1, 'HashLiteral pairs count';
    my $idx = Brocken::AST::Expr::IndexExpr->new( source => $var, index => $const );
    is $idx->source, $var,   'IndexExpr source';
    is $idx->index,  $const, 'IndexExpr index';
    my $mc = Brocken::AST::Expr::MethodCall->new( object => $var, method => 'foo', args => [] );
    is $mc->method, 'foo', 'MethodCall method';
    is $mc->object, $var,  'MethodCall object';
    my $exists = Brocken::AST::Expr::Exists->new( expr => $var );
    is $exists->expr, $var, 'Exists expr';
    my $delete = Brocken::AST::Expr::Delete->new( expr => $var );
    is $delete->expr, $var, 'Delete expr';
    ok $const->isa('Brocken::AST::Node'), 'Expr nodes inherit from Node';
};
subtest 'OOP nodes' => sub {
    my $fd = Brocken::AST::OOP::FieldDecl->new( name => '$id', type => 'Int' );
    is $fd->name, '$id', 'FieldDecl name';
    is $fd->type, 'Int', 'FieldDecl type';
    my $method = Brocken::AST::OOP::Method->new( name => 'get_id', params => [], body => Brocken::AST::Stmt::Block->new( statements => [] ), );
    is $method->name, 'get_id', 'Method name';
    ok scalar( @{ $method->params } ) == 0, 'Method params';
    my $class = Brocken::AST::OOP::ClassDecl->new( name => 'User', fields => [$fd], methods => [$method], );
    is $class->name, 'User', 'ClassDecl name';
    ok scalar( @{ $class->fields } ) == 1,  'one field';
    ok scalar( @{ $class->methods } ) == 1, 'one method';
    is $class->attributes->[0],           undef, 'default attributes';
    is scalar( @{ $class->attributes } ), 0,     'no attributes';
    my $mcall = Brocken::AST::OOP::MethodCall->new( invocant => undef, name => 'new', args => [] );
    is $mcall->name, 'new', 'OOP MethodCall name';
    my $asub = Brocken::AST::OOP::AnonSub->new( params => [], body => undef );
    ok $asub->isa('Brocken::AST::OOP::AnonSub'), 'AnonSub created';
    ok scalar( @{ $asub->params } ) == 0,        'AnonSub params';
    my $native = Brocken::AST::NativeDecl->new( library => 'kernel32', name => 'Sleep', signature => 'void(int)' );
    is $native->library, 'kernel32', 'NativeDecl library';
    is $native->name,    'Sleep',    'NativeDecl name';
};
subtest 'Exception nodes' => sub {
    my $try = Brocken::AST::Exception::TryCatch->new(
        try_block   => Brocken::AST::Stmt::Block->new( statements => [] ),
        catch_var   => { type => 'VAR', value => '$e' },
        catch_block => Brocken::AST::Stmt::Block->new( statements => [] ),
    );
    ok $try->isa('Brocken::AST::Exception::TryCatch'), 'TryCatch created';
    ok $try->try_block,                                'TryCatch try_block';
    ok $try->catch_block,                              'TryCatch catch_block';
    is $try->finally_block, undef, 'TryCatch finally_block default';
    my $die = Brocken::AST::Exception::Die->new( exception => undef );
    ok $die->isa('Brocken::AST::Exception::Die'), 'Die created';
};
subtest 'Async nodes' => sub {
    my $fb = Brocken::AST::Async::FiberBlock->new( body => Brocken::AST::Stmt::Block->new( statements => [] ) );
    ok $fb->isa('Brocken::AST::Async::FiberBlock'), 'FiberBlock created';
    ok scalar( @{ $fb->params } ) == 0,             'FiberBlock default params';
};
done_testing;
