use v5.40;
use utf8;
use feature 'class';
no warnings 'portable', 'experimental::class';
use Test2::V0;
use lib 'lib';
use Brocken::Compiler::Lowering;
use Brocken::Compiler::DataSegment;
use Brocken::Compiler::Pipeline;
subtest 'Lowering instantiation' => sub {
    my $ds     = Brocken::Compiler::DataSegment->new;
    my $driver = Brocken::Compiler::Pipeline->new;
    my $l      = Brocken::Compiler::Lowering->new( data_segment => $ds, driver => $driver );
    ok $l->isa('Brocken::Compiler::Lowering'), 'lowering isa Lowering';
};
subtest 'Lowering program produces instructions' => sub {
    require Brocken::Core::Lexer;
    require Brocken::Core::Parser;
    my $source = 'my Int $x = 42;';
    my $tokens = Brocken::Core::Lexer->new( source => $source )->lex();
    my $ast    = Brocken::Core::Parser->new( tokens => $tokens )->parse();
    my $ds     = Brocken::Compiler::DataSegment->new;
    my $driver = Brocken::Compiler::Pipeline->new;
    my $l      = Brocken::Compiler::Lowering->new( data_segment => $ds, driver => $driver );
    $l->lower_program($ast);
    my @insts = $l->builder->instructions;
    ok scalar(@insts) > 0, 'lower_program produces instructions';
};
subtest 'Lowering with say produces output instructions' => sub {
    require Brocken::Core::Lexer;
    require Brocken::Core::Parser;
    my $source = 'say "hello";';
    my $tokens = Brocken::Core::Lexer->new( source => $source )->lex();
    my $ast    = Brocken::Core::Parser->new( tokens => $tokens )->parse();
    my $ds     = Brocken::Compiler::DataSegment->new;
    my $driver = Brocken::Compiler::Pipeline->new;
    my $l      = Brocken::Compiler::Lowering->new( data_segment => $ds, driver => $driver );
    $l->lower_program($ast);
    my @insts = $l->builder->instructions;
    ok scalar(@insts) > 0, 'say produces instructions';
};
subtest 'Lowering with class produces class IR' => sub {
    require Brocken::Core::Lexer;
    require Brocken::Core::Parser;
    my $source = 'class Foo { field Int $x; method get() { return $x; } }';
    my $tokens = Brocken::Core::Lexer->new( source => $source )->lex();
    my $ast    = Brocken::Core::Parser->new( tokens => $tokens )->parse();
    my $ds     = Brocken::Compiler::DataSegment->new;
    my $driver = Brocken::Compiler::Pipeline->new;
    my $l      = Brocken::Compiler::Lowering->new( data_segment => $ds, driver => $driver );
    $l->lower_program($ast);
    my @insts = $l->builder->instructions;
    ok scalar(@insts) > 0, 'class produces instructions';
};
subtest 'Lowering if/else' => sub {
    require Brocken::Core::Lexer;
    require Brocken::Core::Parser;
    my $source = 'if (1) { say "yes"; } else { say "no"; }';
    my $tokens = Brocken::Core::Lexer->new( source => $source )->lex();
    my $ast    = Brocken::Core::Parser->new( tokens => $tokens )->parse();
    my $ds     = Brocken::Compiler::DataSegment->new;
    my $driver = Brocken::Compiler::Pipeline->new;
    my $l      = Brocken::Compiler::Lowering->new( data_segment => $ds, driver => $driver );
    $l->lower_program($ast);
    my @insts = $l->builder->instructions;
    ok scalar(@insts) > 0, 'if produces instructions';
    my @conds = grep { $_->{op} eq 'cond_br' } @insts;
    ok scalar(@conds) >= 1, 'if produces conditional branch';
};
subtest 'Lowering while loop' => sub {
    require Brocken::Core::Lexer;
    require Brocken::Core::Parser;
    my $source = 'while (0) { say "loop"; }';
    my $tokens = Brocken::Core::Lexer->new( source => $source )->lex();
    my $ast    = Brocken::Core::Parser->new( tokens => $tokens )->parse();
    my $ds     = Brocken::Compiler::DataSegment->new;
    my $driver = Brocken::Compiler::Pipeline->new;
    my $l      = Brocken::Compiler::Lowering->new( data_segment => $ds, driver => $driver );
    $l->lower_program($ast);
    my @insts = $l->builder->instructions;
    ok scalar(@insts) > 0, 'while produces instructions';
    my @jumps = grep { $_->{op} eq 'jmp' } @insts;
    ok scalar(@jumps) >= 1, 'while produces jump (back-edge)';
};
subtest 'Lowering for loop' => sub {
    require Brocken::Core::Lexer;
    require Brocken::Core::Parser;
    my $source = 'for my $x (1..5) { say $x; }';
    my $tokens = Brocken::Core::Lexer->new( source => $source )->lex();
    my $ast    = Brocken::Core::Parser->new( tokens => $tokens )->parse();
    my $ds     = Brocken::Compiler::DataSegment->new;
    my $driver = Brocken::Compiler::Pipeline->new;
    my $l      = Brocken::Compiler::Lowering->new( data_segment => $ds, driver => $driver );
    $l->lower_program($ast);
    my @insts = $l->builder->instructions;
    ok scalar(@insts) > 0, 'for produces instructions';
};
subtest 'Lowering produces call_func for sub calls' => sub {
    require Brocken::Core::Lexer;
    require Brocken::Core::Parser;
    my $source = 'sub foo() { return 1; } foo();';
    my $tokens = Brocken::Core::Lexer->new( source => $source )->lex();
    my $ast    = Brocken::Core::Parser->new( tokens => $tokens )->parse();
    my $ds     = Brocken::Compiler::DataSegment->new;
    my $driver = Brocken::Compiler::Pipeline->new;
    my $l      = Brocken::Compiler::Lowering->new( data_segment => $ds, driver => $driver );
    $l->lower_program($ast);
    my @insts = $l->builder->instructions;
    ok scalar(@insts) > 0, 'sub call produces instructions';
    my @calls = grep { $_->{op} eq 'call_func' || $_->{op} eq 'call_reg' } @insts;
    ok scalar(@calls) >= 1, 'sub produces call instructions';
};
done_testing;
